name: Rucio Release Image CI

on:
  push:
    tags:
      - "release-*.gluex*"

jobs:
  buildx:
    runs-on: ubuntu-latest
    name: Build and Push GlueX Rucio Release Images
    strategy:
      matrix:
        image: [rucio-daemons, rucio-server]
      fail-fast: False

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get git tag name
        id: gittag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"

      - name: Get rucio version
        id: rucioversion
        run: echo "rucio_version=$( echo ${{ env.tag }} |  grep -Eo '[0-9]*\.?[0-9]+\.[0-9]+')" >> "$GITHUB_ENV"
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push the Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./docker/${{ matrix.image }}
          file: ./docker/${{ matrix.image }}/Dockerfile
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.image }}:${{ env.tag }}
          push: true
          build-args: |
            RUCIO_VERSION=${{ env.rucio_version}}